### ISSUE TITLE
Agregador de Código

### ISSUE THREAD

**Issue by SidVal** [SidVal/ABAP#6]
## Agregador de código más intuitivo.

Para lectores y/o usuarios sin conocimientos de GitHub, ni sus interfaces para enviar PR.

Se espera que **[esto](https://sidval.github.io/ABAP/add.html)** funcione, pero está dando error.

***

Se está probando **StaticMan** (ver **[idea](https://github.com/SidVal/SidV/issues/8)**)

https://staticman.net/docs/

**Comment by SidVal** [comment]
Llegué hasta acá:
https://github.com/eduardoboucas/staticman/issues/101

**Comment by SidVal** [comment]
Encontré estos sitios:

https://mademistakes.com/articles/improving-jekyll-static-comments/
https://mademistakes.com/articles/jekyll-static-comments/

Tienen data muy interesante, y con algunas otras pruebas ahora funciona :dancing_women:

**Comment by SidVal** [comment]
Está funcionando correctamente, ahora lo que hay que pensar es cómo hacer para que desde el _agregador_, cargue el _readme_ del código por un lado, y el código propiamente dicho por otro lado. :thinking:  

No se me ocurre posibilidad, ya que el `add.html` permite un pull-request con un solo archivo.
Desconozco si **staticman** puede enviar dos archivos distintos por PR.

Pareciera que es esto de las múltiples instancias: https://github.com/eduardoboucas/staticman/issues/32
Habría que ver cómo funciona, y hacer pruebas :+1:

**Comment by SidVal** [comment]
Devuelvo la categoría de :bug:  
Tengo un problema cuando sube el código el usuario, en caso de que no pueda hacer lo de dos instancias (que por el momento no puedo probar).

El body del archivo que se envía, aún no es el código en sí que carga el usuario.
Lo estoy siguiendo aquí al issue reportado en la fuente: https://github.com/eduardoboucas/staticman/issues/91

**Comment by SidVal** [comment]
Se corrieron algunas pruebas con esta definición:
https://github.com/SidVal/ABAP/blob/master/staticman.yml

```
codigos:
  allowedFields: ["titulo", "autor", "url", "descripcion", "codigo"]
  branch: "master"
  commitMessage: "Código Nuevo: {fields.titulo}"
  pullRequestBody: "Un usuario quiere subir el siguiente archivo; ¿estamos de acuerdo?"
  filename: "{fields.titulo}/{fields.titulo}"
  generatedFields:
     date:
       type: "date"
       options:
         format: "iso8601"
  moderation: true
  path: "codigos"
  requiredFields: ["titulo", "autor", "url", "descripcion", "codigo"]
  format: "frontmatter"
  transforms:
    codigo: "frontmatterContent"
  extension: "abap"
```

Sin embargo:

PR: https://github.com/SidVal/ABAP/pull/12
Archivo: https://github.com/SidVal/ABAP/pull/12/files

No cumple lo del cuerpo del archivo.
**El código se ve en la cabecera y no en el cuerpo (body)**

```
---
_id: ae93fe00-61ec-11e7-abb2-050f30cdd33c
titulo: otra prueba
autor: ver carpeta
url: 'http://www.pepe.com'
descripcion: descripción
codigo: "codigo abap\r\nbla bla\r\n\r\nbla bla\r\n\r\nespacio\r\n\r\nfin"
date: '2017-07-06T01:44:43.053Z'
---
undefined
```

**Comment by SidVal** [comment]
Ehhh la versión 3 funciona bien!

Quedó así:

```
--- 
codigos: 
  allowedFields: 
    - titulo
    - autor
    - url
    - descripcion
    - codigo
  allowedOrigins: 
    - localhost
    - sidval.github.io
  branch: master
  commitMessage: "Código Nuevo: {fields.titulo}"
  filename: "{fields.titulo}"
  format: "frontmatter"
  generatedFields: 
    date: 
      options: 
        format: iso8601
      type: date
  moderation: true
  name: "Repo SAP ABAP"
  path: "codigos/{fields.titulo}"
  pullRequestBody: "Un usuario quiere subir el siguiente archivo; **¿estamos de acuerdo?** \n\n"
  requiredFields: 
    - titulo
    - autor
    - url
    - descripcion
    - codigo
  transforms:
    codigo: frontmatterContent
  extension: "abap"
```


https://github.com/SidVal/ABAP/pull/31/files
```
+---
 +_id: 105c9000-7130-11e7-b597-5f8c890efa0b
 +titulo: titulo
 +descripcion: fsfsdfsdf
 +autor: sid
 +url: 'http://www.pepe.com'
 +date: '2017-07-25T11:54:50.953Z'
 +---
 +codigo1
```
